import Link from "next/link";
import { pageMetadata } from "../seo";
import { LegalLayout } from "../legal-layout";
export const metadata = pageMetadata("Privacy Policy", "How Creative Pie handles website visits, project enquiries and your privacy choices.", "/privacy");
export default function PrivacyPage() {
 return <LegalLayout title="Privacy policy." intro="What we process, why we need it, and how to contact us about your information.">
  <section><h2>Who this notice covers</h2><p>Creative Pie is the creative-services business presented on this website, based in Lagos, Nigeria. This notice covers this portfolio website and enquiries you choose to send to Creative Pie. It does not replace the privacy notices of services you visit through external links.</p></section>
  <section><h2>Your project brief stays with you</h2><p>The enquiry form is a message-preparation tool. It asks for a name or company and a short brief. Email and service selection are optional. The website does not submit the form to a server, save it in a database, or add you to a mailing list.</p><p>Choosing “Copy project brief” prepares the message in this page and attempts to copy it to your device clipboard. You decide whether to open Instagram, paste the text and send it. Drafts are held in page memory; your browser or operating system may retain clipboard history under its own settings.</p><p>Please do not include passwords, payment-card information, identity documents, health information or personal information about other people in a project brief.</p></section>
  <section><h2>If you send us an enquiry</h2><p>We use the information you send and your reply contact to respond, discuss your requirements and prepare a proposal at your request. The basis for that processing is taking steps towards a contract, or performing an agreed project. Only information needed for those purposes should be shared.</p><p>Project administration and legally required records may also be processed to meet legal obligations. Necessary security and misuse prevention may rely on legitimate interests, with consideration for your rights. We do not use the enquiry form to request marketing consent. Any future marketing subscription will require a separate, optional choice.</p></section>
  <section><h2>Website delivery, cookies and analytics</h2><p>Our hosting providers process technical request information, such as IP address, requested page, time and browser information, to deliver and secure the website. Provider security and operational logs are separate from the enquiry form.</p><p>The website code does not enable advertising pixels, visitor analytics, session recording or third-party media embeds. Fonts and portfolio images are served with the site. See our <Link href="/cookies">cookie policy</Link> for the current browser-storage details.</p></section>
  <section><h2>Services and access to information</h2><p>The site is delivered through hosting infrastructure provided by Vercel and/or OpenAI Sites with Cloudflare, depending on the address visited. Instagram/Meta processes a visit or message when you choose to use its service. These providers may process information outside Nigeria. Their own privacy notices explain their processing. Creative Pie remains responsible for meeting the data-protection requirements that apply to processing and transfers it arranges.</p><p>If a project needs collaborators, information shared with them should be limited to the agreed work and handled confidentially. We do not sell enquiry information. Any legally required disclosure must have an applicable basis. A link click or this notice does not itself constitute consent to an international transfer.</p></section>
  <section><h2>How long information is kept</h2><p>Unsent form drafts last only while this page remains open. For an enquiry you send that does not lead to a contract, our policy is to delete pre-contract personal information within six months, unless retaining it is justified for a legal claim. Project and transaction records are kept only for the work and applicable legal, accounting or dispute requirements, then deleted or anonymised when no longer needed.</p><p>Instagram messages and hosting logs are also subject to the provider’s retention arrangements. Deleting information from our working records cannot remove copies independently retained by a platform.</p></section>
  <section><h2>Your choices and rights</h2><p>Subject to applicable law, you may request access to or correction of your information, deletion, restriction or portability, and object to certain processing. Where processing relies on consent, you may withdraw it without affecting earlier lawful processing. Creative Pie does not use this enquiry flow for automated decisions about you.</p><p>Contact us using the details below and describe the request. We may ask for proportionate information to verify it; please do not send identity documents unless needed and specifically requested through an appropriate channel. You can also complain to the <a href="https://ndpc.gov.ng/" target="_blank" rel="noopener noreferrer">Nigeria Data Protection Commission</a>.</p></section>
  <section><h2>Changes</h2><p>We will update this notice when the website’s processing changes. Optional tracking or marketing will not be enabled merely because this notice changes; any consent required for it must be obtained first.</p></section>
 </LegalLayout>;
}
