import Link from "next/link";
import { pageMetadata } from "../seo";
import { LegalLayout } from "../legal-layout";
export const metadata = pageMetadata("Terms and Conditions", "Terms for using Creative Pie’s portfolio website and making a project enquiry.", "/terms");
export default function TermsPage() {
 return <LegalLayout title="Terms & conditions." intro="Using this website, making an enquiry and agreeing a creative project.">
  <section><h2>About this website</h2><p>This website presents Creative Pie’s creative services and portfolio. It does not take online payments or automatically book a service. Sending an enquiry does not reserve a date or create an obligation to purchase.</p></section>
  <section><h2>Project agreements</h2><p>Before work or payment, the parties should agree a written proposal or project agreement identifying the contracting business, scope, deliverables, timing, fees, applicable taxes, payment schedule, revisions and responsibilities. Any transfer or licence of intellectual-property rights should be stated there too.</p><p>Project-specific terms govern the agreed service, subject to applicable law. These website terms do not replace that agreement or remove rights that cannot legally be excluded.</p></section>
  <section><h2>Portfolio and outcomes</h2><p>Portfolio work illustrates a creative approach and is not a promise of particular sales, views, engagement or business results. Availability and project requirements are confirmed individually. Illustrative brand concepts do not represent a claim to own the places or equipment shown.</p></section>
  <section><h2>Images, names and creative work</h2><p>Materials on the website may belong to Creative Pie, clients, photographers or other rights holders. Access to the website does not grant permission to reproduce, sell or reuse those materials. Brand names identify the work shown and do not imply a wider endorsement.</p><p>If you believe a credit or permission is missing, contact us with the page, material and basis of your request so it can be reviewed. When supplying project materials, tell us about any licence conditions or third-party permissions that apply.</p></section>
  <section><h2>Using the website responsibly</h2><p>Do not misuse the website, interfere with its operation, attempt unauthorised access or send unlawful material. Share only information and project material that you are entitled to provide.</p></section>
  <section><h2>Privacy and external links</h2><p>Our <Link href="/privacy">privacy and cookie notice</Link> explains the enquiry and website setup. External services, including Instagram, operate under their own terms. Opening an external link does not submit your unsent project brief.</p></section>
  <section id="cancellations"><h2>Cancellations &amp; refunds</h2><p>Cancellation, rescheduling and deposit terms must be agreed in writing before payment. This website does not impose a blanket “no refunds” rule. Contact Creative Pie as soon as possible with your project reference and the change or concern; do not send full payment-card details.</p><p>Any cancellation charge must be lawful and reasonable, taking account of the agreement, work completed, documented commitments made for your project and your applicable rights. Rescheduling depends on availability; additional costs should be explained and agreed before they are incurred.</p><p>If we cannot deliver an agreed service, or the work does not meet the agreed scope or required standard, we will review the concern and discuss correction, completion or an appropriate refund where required. A revision allowance does not remove statutory remedies, and you do not have to accept a substitute where the law entitles you to another remedy.</p><p>For an agreed refund, we will confirm the amount, payment method and expected processing time in writing, subject to any legal deadline. Payment-provider processing may affect when it reaches your account. Your mandatory consumer rights remain unaffected.</p></section>
  <section><h2>Problems and applicable law</h2><p>Contact Creative Pie if something on the website is inaccurate or a service concern arises. Nigerian law is relevant to our Lagos-based operations; mandatory protections in another applicable jurisdiction are not excluded by these terms. Nothing here excludes liability or remedies that cannot lawfully be excluded.</p><p>We may update website information and these terms. Changes do not retrospectively alter an existing signed project agreement without the agreement or lawful basis required for that change.</p></section>
 </LegalLayout>;
}
