import { pageMetadata } from "../seo";
import { LegalLayout } from "../legal-layout";
export const metadata = pageMetadata("Refunds and Cancellations", "How to raise a cancellation, rescheduling, refund or service concern with Creative Pie.", "/refunds");
export default function RefundsPage() {
 return <LegalLayout title="Refunds & cancellations." intro="Clear arrangements before payment, and a direct route to resolve a concern.">
  <section><h2>Before a project starts</h2><p>This website does not take payments. Creative services are quoted and agreed separately. Before paying, ask for the written scope, delivery schedule, total price, payment milestones, revision allowance, and cancellation or rescheduling terms.</p><p>This website does not impose a blanket “no refunds” rule or declare every deposit non-refundable. Any proposed charge or restriction must be explained before payment and comply with applicable law.</p></section>
  <section><h2>If you need to cancel or reschedule</h2><p>Contact Creative Pie as soon as possible using the details below. Include your name, project reference if available, and the change requested. Do not send full payment-card details.</p><p>Any amount payable or refundable should be assessed against the written agreement, work actually completed, reasonable and documented commitments made for your project, and your applicable rights. Cancellation charges must be lawful and reasonable. Rescheduling depends on team and supplier availability; additional costs should be explained and agreed before they are incurred.</p></section>
  <section><h2>If we cannot deliver</h2><p>If Creative Pie cannot provide an agreed service, we will discuss an appropriate remedy, which may include a revised delivery arrangement or repayment for undelivered services, taking account of the agreement and applicable law. We will not require you to accept a substitute where you are legally entitled to another remedy.</p></section>
  <section><h2>If something is wrong with the work</h2><p>Tell us what does not match the agreed scope or required service standard, with relevant examples. We will review the concern and discuss correction, completion or an appropriate refund where required. An agreed revision allowance does not remove statutory remedies for deficient services.</p></section>
  <section><h2>How an agreed refund is handled</h2><p>We will confirm the amount, payment method and expected processing time in writing, subject to any deadline required by law. Payment-provider processing times may affect when money appears in your account.</p><p>This policy does not restrict mandatory consumer rights under Nigerian law or other applicable law. Project-specific terms cannot override rights that cannot legally be waived.</p></section>
 </LegalLayout>;
}
